import type { Builder } from '@/lib/types'

const avatar = (slug: string) => `https://api.dicebear.com/9.x/notionists/svg?seed=${slug}&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf`

const gallery = (slug: string): string[] => [
  `https://picsum.photos/seed/${slug}1/800/400`,
  `https://picsum.photos/seed/${slug}2/800/400`,
  `https://picsum.photos/seed/${slug}3/800/400`,
]

export const builders: Builder[] = [
  { id: '1',  name: '李思琪',     slug: 'li-siqi',      avatar_url: avatar('li-siqi'),      track: 'Founder',  region: '中国大陆',   bio: 'DeFi 协议联合创始人，前蚂蚁链工程师，致力于链上衍生品创新。', twitter: '@siqi_li', xiaohongshu: 'siqi_web3', projects: ['PerpDEX Protocol', 'Liquidity Layer'], gallery: gallery('li-siqi'),      score: 98.5, rank: 1 },
  { id: '2',  name: 'Vivian Chen', slug: 'vivian-chen',   avatar_url: avatar('vivian-chen'),   track: 'Founder',  region: '新加坡',      bio: 'Solana 生态 NFT 交易平台创始人，前 Binance Labs 投资经理。', twitter: '@vivianchen', xiaohongshu: '', projects: ['NFTrade', 'Solana Builder DAO'], gallery: gallery('vivian-chen'),   score: 97.8, rank: 2 },
  { id: '3',  name: '张雨桐',     slug: 'zhang-yutong',  avatar_url: avatar('zhang-yutong'),  track: 'Builder',  region: '中国大陆',   bio: 'Ethereum 核心开发者，EIP-4337 贡献者，专注于账户抽象与智能合约钱包。', twitter: '@yutong_eth', xiaohongshu: 'yutong_dev', projects: ['Account Abstraction SDK', 'ERC-4337 Bundler'], gallery: gallery('zhang-yutong'),  score: 97.2, rank: 3 },
  { id: '4',  name: 'Mia Wang',    slug: 'mia-wang',      avatar_url: avatar('mia-wang'),      track: 'KOL',      region: '中国香港',   bio: 'Web3 华语区头部 KOL，全网粉丝 500 万，前华尔街投行分析师。', twitter: '@miawang_web3', xiaohongshu: 'mia_web3', projects: ['Web3 Academy', 'Mia Talks Crypto'], gallery: gallery('mia-wang'),      score: 96.5, rank: 4 },
  { id: '5',  name: '陈晓琳',     slug: 'chen-xiaolin',  avatar_url: avatar('chen-xiaolin'),  track: 'Investor', region: '中国大陆',   bio: 'Fenbushi Capital 合伙人，专注投资基础设施与 DeFi 赛道。', twitter: '@xiaolin_chen', xiaohongshu: '', projects: ['50+ Portfolio', 'Web3 Builder Grant'], gallery: gallery('chen-xiaolin'),  score: 96.0, rank: 5 },
  { id: '6',  name: 'Tina Zhao',   slug: 'tina-zhao',     avatar_url: avatar('tina-zhao'),     track: 'Founder',  region: '中国大陆',   bio: 'ZK 隐私协议创始人，清华大学密码学博士，曾获 ETHGlobal 黑客松冠军。', twitter: '@tinazhao', xiaohongshu: 'tinazk', projects: ['Privacy Layer', 'ZK-Rollup SDK'], gallery: gallery('tina-zhao'),     score: 95.6, rank: 6 },
  { id: '7',  name: 'Sarah Liu',   slug: 'sarah-liu',     avatar_url: avatar('sarah-liu'),     track: 'Builder',  region: '北美',        bio: '前 Google AI 研究员，现全链游戏引擎核心开发者，Rust 高手。', twitter: '@saraliu_dev', xiaohongshu: '', projects: ['On-Chain Game Engine', 'ECS Framework'], gallery: gallery('sarah-liu'),     score: 95.1, rank: 7 },
  { id: '8',  name: '王静怡',     slug: 'wang-jingyi',    avatar_url: avatar('wang-jingyi'),    track: 'KOL',      region: '中国台湾',   bio: '知名 DeFi 研究员，每周发布链上数据分析报告，付费订阅用户 2 万+。', twitter: '@jingyi_defi', xiaohongshu: 'jingyi_research', projects: ['DeFi Insights', 'Chain Data Weekly'], gallery: gallery('wang-jingyi'),    score: 94.7, rank: 8 },
  { id: '9',  name: 'Rachel Ng',   slug: 'rachel-ng',     avatar_url: avatar('rachel-ng'),     track: 'Investor', region: '新加坡',      bio: 'Spartan Group 投资总监，专注亚太区 Web3 初创企业。', twitter: '@rachelng', xiaohongshu: '', projects: ['30+ APAC Deals', 'Builder Accelerator'], gallery: gallery('rachel-ng'),     score: 94.3, rank: 9 },
  { id: '10', name: '林嘉欣',     slug: 'lin-jiaxin',    avatar_url: avatar('lin-jiaxin'),    track: 'Founder',  region: '中国大陆',   bio: 'DAO 治理工具平台创始人，前字节跳动产品经理，连续创业者。', twitter: '@jiaxin_lin', xiaohongshu: 'jiaxin_dao', projects: ['DAO Tool Suite', 'Governance Framework'], gallery: gallery('lin-jiaxin'),    score: 93.9, rank: 10 },
  { id: '11', name: 'Emily Zhang', slug: 'emily-zhang',    avatar_url: avatar('emily-zhang'),    track: 'Builder',  region: '北美',        bio: '全栈 Web3 开发者，开源贡献者，OpenZeppelin 合约审计员。', twitter: '@emilyzhang', xiaohongshu: 'emily_crypto', projects: ['Open Source Library', 'Audit Tool'], gallery: gallery('emily-zhang'),    score: 93.5, rank: 11 },
  { id: '12', name: '赵思涵',     slug: 'zhao-sihan',    avatar_url: avatar('zhao-sihan'),    track: 'Founder',  region: '中国大陆',   bio: 'SocialFi 平台创始人，前小红书产品总监，深度融合 Web2 与 Web3。', twitter: '@sihan_zhao', xiaohongshu: 'sihan_socialfi', projects: ['SocialFi Platform', 'Creator Economy Protocol'], gallery: gallery('zhao-sihan'),    score: 93.0, rank: 12 },
  { id: '13', name: 'Helen Wu',    slug: 'helen-wu',      avatar_url: avatar('helen-wu'),      track: 'KOL',      region: '中国大陆',   bio: '区块链法律合规博主，北大法学博士，专注 Web3 监管政策解读。', twitter: '@helenwu_law', xiaohongshu: 'helen_blockchain', projects: ['Crypto Law Blog', 'Compliance Guide'], gallery: gallery('helen-wu'),      score: 92.6, rank: 13 },
  { id: '14', name: 'Grace Park',  slug: 'grace-park',    avatar_url: avatar('grace-park'),    track: 'Investor', region: '中国香港',   bio: 'Animoca Brands 投资副总裁，聚焦 GameFi 与元宇宙赛道。', twitter: '@gracepark', xiaohongshu: '', projects: ['20+ GameFi Investments', 'Metaverse Fund'], gallery: gallery('grace-park'),    score: 92.2, rank: 14 },
  { id: '15', name: '刘雅馨',     slug: 'liu-yaxin',     avatar_url: avatar('liu-yaxin'),     track: 'Builder',  region: '中国大陆',   bio: '跨链互操作协议核心开发者，Cosmos IBC 贡献者。', twitter: '@yaxin_cosmos', xiaohongshu: 'yaxin_dev', projects: ['IBC Bridge', 'Cross-Chain SDK'], gallery: gallery('liu-yaxin'),     score: 91.8, rank: 15 },
  { id: '16', name: 'Amy Chen',    slug: 'amy-chen',      avatar_url: avatar('amy-chen'),      track: 'Founder',  region: '新加坡',      bio: 'Web3 教育平台创始人，前 Udemy 课程总监，累计培养 10 万+ 区块链开发者。', twitter: '@amychen_edu', xiaohongshu: 'amy_web3edu', projects: ['Blockchain Academy', 'Dev Bootcamp'], gallery: gallery('amy-chen'),      score: 91.4, rank: 16 },
  { id: '17', name: '吴佳怡',     slug: 'wu-jiayi',      avatar_url: avatar('wu-jiayi'),      track: 'KOL',      region: '中国大陆',   bio: 'NFT 艺术策展人，数字艺术家，作品在苏富比拍卖超过 100 ETH。', twitter: '@jiayi_nft', xiaohongshu: 'jiayi_art', projects: ['Crypto Art Gallery', 'NFT Curation Platform'], gallery: gallery('wu-jiayi'),      score: 91.0, rank: 17 },
  { id: '18', name: 'Diana Li',    slug: 'diana-li',      avatar_url: avatar('diana-li'),      track: 'Builder',  region: '北美',        bio: 'Solana 基金会开发者关系负责人，前 Stripe 工程师。', twitter: '@dianali_sol', xiaohongshu: '', projects: ['Solana Developer Program', 'Starter Kits'], gallery: gallery('diana-li'),      score: 90.6, rank: 18 },
  { id: '19', name: '杨思雨',     slug: 'yang-siyu',     avatar_url: avatar('yang-siyu'),     track: 'Founder',  region: '中国大陆',   bio: '链上数据分析平台创始人，前 Glassnode 亚太区负责人。', twitter: '@siyu_yang', xiaohongshu: 'siyu_data', projects: ['On-Chain Analytics', 'Data Dashboard'], gallery: gallery('yang-siyu'),     score: 90.2, rank: 19 },
  { id: '20', name: 'Julia Kim',   slug: 'julia-kim',     avatar_url: avatar('julia-kim'),     track: 'Investor', region: '韩国',        bio: 'Hashed 合伙人，专注 Web3 基础设施与消费级应用投资。', twitter: '@juliakim', xiaohongshu: '', projects: ['40+ Portfolio', 'Ecosystem Fund'], gallery: gallery('julia-kim'),     score: 89.8, rank: 20 },
  { id: '21', name: '黄芷若',     slug: 'huang-zhiruo',  avatar_url: avatar('huang-zhiruo'),  track: 'Builder',  region: '中国大陆',   bio: '零知识证明工程师，前 Alibaba 达摩院研究员，zk-SNARK 电路专家。', twitter: '@zhiruo_zk', xiaohongshu: 'zhiruo_crypto', projects: ['ZK-Circuits Library', 'Privacy SDK'], gallery: gallery('huang-zhiruo'),  score: 89.4, rank: 21 },
  { id: '22', name: 'Rebecca Tan', slug: 'rebecca-tan',   avatar_url: avatar('rebecca-tan'),   track: 'KOL',      region: '新加坡',      bio: 'The Block 亚太主编，资深加密媒体人，采访过 100+ Web3 创始人。', twitter: '@rebeccatan', xiaohongshu: '', projects: ['Crypto Media', 'Founder Interviews'], gallery: gallery('rebecca-tan'),   score: 89.0, rank: 22 },
  { id: '23', name: '周雨萱',     slug: 'zhou-yuxuan',   avatar_url: avatar('zhou-yuxuan'),   track: 'Founder',  region: '中国大陆',   bio: '链上声誉系统创始人，前腾讯高级工程师，专注 DID 赛道。', twitter: '@yuxuan_did', xiaohongshu: 'yuxuan_web3', projects: ['On-Chain Reputation', 'DID Protocol'], gallery: gallery('zhou-yuxuan'),   score: 88.6, rank: 23 },
  { id: '24', name: 'Nina Patel',  slug: 'nina-patel',    avatar_url: avatar('nina-patel'),    track: 'Builder',  region: '欧洲',        bio: '以太坊基金会研究员，专注 MEV 与 PBS 方向，发表多篇学术论文。', twitter: '@ninapatel_eth', xiaohongshu: '', projects: ['MEV Research', 'PBS Implementation'], gallery: gallery('nina-patel'),    score: 88.2, rank: 24 },
  { id: '25', name: '郑悦然',     slug: 'zheng-yueran',  avatar_url: avatar('zheng-yueran'),  track: 'KOL',      region: '中国大陆',   bio: 'Crypto 交易策略博主，前量化交易员，YouTube 订阅 30 万。', twitter: '@yueran_trade', xiaohongshu: 'yueran_trader', projects: ['Trading Academy', 'Signal Bot'], gallery: gallery('zheng-yueran'),  score: 87.8, rank: 25 },
  { id: '26', name: 'Sofia Rossi', slug: 'sofia-rossi',   avatar_url: avatar('sofia-rossi'),   track: 'Founder',  region: '欧洲',        bio: 'DeSci 去中心化科学平台创始人，剑桥大学生物信息学博士。', twitter: '@sofiarossi', xiaohongshu: '', projects: ['DeSci Platform', 'Research DAO'], gallery: gallery('sofia-rossi'),   score: 87.4, rank: 26 },
  { id: '27', name: '孙悦',       slug: 'sun-yue',       avatar_url: avatar('sun-yue'),       track: 'Builder',  region: '中国大陆',   bio: 'Move 语言智能合约专家，Aptos 生态系统核心贡献者。', twitter: '@sunyue_move', xiaohongshu: 'sunyue_dev', projects: ['Move Framework', 'Aptos DApp Templates'], gallery: gallery('sun-yue'),       score: 87.0, rank: 27 },
  { id: '28', name: 'Lily Ho',     slug: 'lily-ho',       avatar_url: avatar('lily-ho'),       track: 'Investor', region: '中国香港',   bio: 'IOSG Ventures 合伙人，专注 Layer1/Layer2 基础设施投资。', twitter: '@lilyho_vc', xiaohongshu: '', projects: ['25+ Infra Investments', 'Research Reports'], gallery: gallery('lily-ho'),       score: 86.6, rank: 28 },
  { id: '29', name: '许静',       slug: 'xu-jing',       avatar_url: avatar('xu-jing'),       track: 'Founder',  region: '中国大陆',   bio: 'Web3 招聘平台创始人，前 LinkedIn 中国区产品负责人。', twitter: '@xujing_web3', xiaohongshu: 'xujing_talent', projects: ['Web3 Talent Platform', 'Job Matching Protocol'], gallery: gallery('xu-jing'),       score: 86.2, rank: 29 },
  { id: '30', name: 'Anna Muller', slug: 'anna-muller',   avatar_url: avatar('anna-muller'),   track: 'Builder',  region: '欧洲',        bio: 'Polkadot 平行链开发者，Substrate 框架贡献者，Rust 社区活跃成员。', twitter: '@annamuller_dot', xiaohongshu: '', projects: ['Parachain Template', 'Substrate Pallets'], gallery: gallery('anna-muller'),   score: 85.8, rank: 30 },
  { id: '31', name: '唐艺菲',     slug: 'tang-yifei',    avatar_url: avatar('tang-yifei'),    track: 'KOL',      region: '中国大陆',   bio: 'GameFi 赛道分析师，前腾讯游戏运营，深度研究 Web3 游戏经济学。', twitter: '@yifei_gamefi', xiaohongshu: 'yifei_gaming', projects: ['GameFi Reports', 'Tokenomics Analysis'], gallery: gallery('tang-yifei'),    score: 85.4, rank: 31 },
  { id: '32', name: 'Cindy Gao',   slug: 'cindy-gao',     avatar_url: avatar('cindy-gao'),     track: 'Founder',  region: '中国大陆',   bio: '链上保险协议创始人，前众安保险精算师，首创参数化理赔。', twitter: '@cindygao', xiaohongshu: 'cindy_insurance', projects: ['On-Chain Insurance', 'Parametric Claims'], gallery: gallery('cindy-gao'),     score: 85.0, rank: 32 },
  { id: '33', name: '沈沛妮',     slug: 'shen-peini',    avatar_url: avatar('shen-peini'),    track: 'Builder',  region: '中国台湾',   bio: '全栈 Web3 工程师，React Native 跨链钱包核心开发者。', twitter: '@peini_shen', xiaohongshu: 'peini_wallet', projects: ['Cross-Chain Wallet', 'Mobile SDK'], gallery: gallery('shen-peini'),    score: 84.6, rank: 33 },
  { id: '34', name: 'Maria Santos',slug: 'maria-santos',  avatar_url: avatar('maria-santos'),  track: 'Investor', region: '北美',        bio: 'a16z Crypto 投资合伙人，前 Coinbase 战略副总裁。', twitter: '@mariasantos', xiaohongshu: '', projects: ['Top-tier Portfolio', 'Crypto Fund'], gallery: gallery('maria-santos'),  score: 84.2, rank: 34 },
  { id: '35', name: '丁梦瑶',     slug: 'ding-mengyao',  avatar_url: avatar('ding-mengyao'),  track: 'Founder',  region: '中国大陆',   bio: 'RWA 资产代币化平台创始人，前 Citi 投行部副总裁。', twitter: '@mengyao_rwa', xiaohongshu: 'mengyao_finance', projects: ['RWA Tokenization', 'Asset Bridge'], gallery: gallery('ding-mengyao'),  score: 83.8, rank: 35 },
  { id: '36', name: 'Laura Wang',  slug: 'laura-wang',    avatar_url: avatar('laura-wang'),    track: 'Builder',  region: '中国大陆',   bio: '智能合约安全审计师，前 Trail of Bits 工程师，发现 50+ 高危漏洞。', twitter: '@laurawang_sec', xiaohongshu: 'laura_security', projects: ['Security Audit Reports', 'Vulnerability DB'], gallery: gallery('laura-wang'),    score: 83.4, rank: 36 },
  { id: '37', name: 'Ella Fischer',slug: 'ella-fischer',  avatar_url: avatar('ella-fischer'),  track: 'KOL',      region: '欧洲',        bio: 'Web3 开发者教育博主，YouTube 全栈教程系列播放量破千万。', twitter: '@ellafischer', xiaohongshu: '', projects: ['Dev Tutorials', 'Code Along Series'], gallery: gallery('ella-fischer'),  score: 83.0, rank: 37 },
  { id: '38', name: '江欣妍',     slug: 'jiang-xinyan',  avatar_url: avatar('jiang-xinyan'),  track: 'Founder',  region: '中国大陆',   bio: '去中心化存储网络创始人，前华为云存储架构师。', twitter: '@xinyan_storage', xiaohongshu: 'xinyan_web3', projects: ['Decentralized Storage', 'Data Availability Layer'], gallery: gallery('jiang-xinyan'),  score: 82.6, rank: 38 },
  { id: '39', name: 'Katie Brown', slug: 'katie-brown',   avatar_url: avatar('katie-brown'),   track: 'Investor', region: '北美',        bio: 'Dragonfly Capital 投资经理，聚焦 DeFi 与隐私赛道。', twitter: '@katiebrown_vc', xiaohongshu: '', projects: ['15+ DeFi Deals', 'Market Analysis'], gallery: gallery('katie-brown'),   score: 82.2, rank: 39 },
  { id: '40', name: '范佳琪',     slug: 'fan-jiaqi',     avatar_url: avatar('fan-jiaqi'),     track: 'Builder',  region: '中国大陆',   bio: '前端架构师，Web3 UI 组件库作者，开源项目 GitHub 5000+ Star。', twitter: '@jiaqi_ui', xiaohongshu: 'jiaqi_design', projects: ['Web3 UI Kit', 'Component Library'], gallery: gallery('fan-jiaqi'),     score: 81.8, rank: 40 },
  { id: '41', name: 'Yuki Tanaka', slug: 'yuki-tanaka',   avatar_url: avatar('yuki-tanaka'),   track: 'Founder',  region: '日本',        bio: 'NFT IP 协议创始人，前万代南梦宫 IP 授权总监。', twitter: '@yukitanaka_nft', xiaohongshu: '', projects: ['NFT IP Protocol', 'Creator Tools'], gallery: gallery('yuki-tanaka'),   score: 81.4, rank: 41 },
  { id: '42', name: '秦洛',       slug: 'qin-luo',       avatar_url: avatar('qin-luo'),       track: 'KOL',      region: '中国大陆',   bio: 'Web3 创业播客主持人，采访 200+ Web3 创始人，Spotify 华语区 Top 10。', twitter: '@qinluo_podcast', xiaohongshu: 'qinluo_web3', projects: ['Web3 Podcast', 'Founder Stories'], gallery: gallery('qin-luo'),       score: 81.0, rank: 42 },
  { id: '43', name: 'Iris Moon',   slug: 'iris-moon',     avatar_url: avatar('iris-moon'),     track: 'Builder',  region: '新加坡',      bio: '预言机网络核心开发者，Chainlink 社区大使，Solidity 讲师。', twitter: '@irismoon_link', xiaohongshu: 'iris_oracle', projects: ['Oracle Integration', 'Solidity Course'], gallery: gallery('iris-moon'),     score: 80.6, rank: 43 },
  { id: '44', name: '乔雨薇',     slug: 'qiao-yuwei',    avatar_url: avatar('qiao-yuwei'),    track: 'Founder',  region: '中国大陆',   bio: '链上身份验证协议创始人，前公安部第三研究所研究员。', twitter: '@yuwei_id', xiaohongshu: 'yuwei_identity', projects: ['Identity Protocol', 'KYC Oracle'], gallery: gallery('qiao-yuwei'),    score: 80.2, rank: 44 },
  { id: '45', name: 'Hannah Lee',  slug: 'hannah-lee',    avatar_url: avatar('hannah-lee'),    track: 'Investor', region: '中国香港',   bio: 'CMT Digital 交易主管，专注二级市场与做市策略。', twitter: '@hannahlee_trade', xiaohongshu: '', projects: ['Market Making', 'Trading Desk'], gallery: gallery('hannah-lee'),    score: 79.8, rank: 45 },
  { id: '46', name: '袁诗涵',     slug: 'yuan-shihan',   avatar_url: avatar('yuan-shihan'),   track: 'KOL',      region: '中国大陆',   bio: 'Web3 设计师转型 KOL，Figma Web3 设计系统作者，Dribbble 推荐设计师。', twitter: '@shihan_design', xiaohongshu: 'shihan_design', projects: ['Web3 Design System', 'UI/UX Guide'], gallery: gallery('yuan-shihan'),   score: 79.4, rank: 46 },
  { id: '47', name: 'Tanya Gupta', slug: 'tanya-gupta',   avatar_url: avatar('tanya-gupta'),   track: 'Builder',  region: '新加坡',      bio: 'DeFi 协议后端工程师，Go 语言专家，高频交易系统架构师。', twitter: '@tanyagupta_dev', xiaohongshu: '', projects: ['DeFi Backend', 'HFT Infrastructure'], gallery: gallery('tanya-gupta'),   score: 79.0, rank: 47 },
  { id: '48', name: '蔡舒婷',     slug: 'cai-shuting',   avatar_url: avatar('cai-shuting'),   track: 'Founder',  region: '中国台湾',   bio: 'DAO 法律框架平台创始人，台湾首位区块链法律专业律师。', twitter: '@shuting_law', xiaohongshu: 'shuting_dao', projects: ['DAO Legal Framework', 'Compliance Tool'], gallery: gallery('cai-shuting'),   score: 78.6, rank: 48 },
  { id: '49', name: 'Zara Ahmed',  slug: 'zara-ahmed',    avatar_url: avatar('zara-ahmed'),    track: 'KOL',      region: '欧洲',        bio: 'Crypto 经济学研究员，LSE 经济学博士，Tokenomics 设计顾问。', twitter: '@zaraahmed_econ', xiaohongshu: '', projects: ['Tokenomics Design', 'Research Papers'], gallery: gallery('zara-ahmed'),    score: 78.2, rank: 49 },
  { id: '50', name: '谭雨晴',     slug: 'tan-yuqing',    avatar_url: avatar('tan-yuqing'),    track: 'Builder',  region: '中国大陆',   bio: '全链游戏客户端开发者，Unity + Web3 技术栈，多款链游主程。', twitter: '@yuqing_game', xiaohongshu: 'yuqing_gamedev', projects: ['On-Chain Game Client', 'Unity SDK'], gallery: gallery('tan-yuqing'),    score: 77.8, rank: 50 },
]

export function getBuilders(): Builder[] {
  return builders
}

export function getBuilderBySlug(slug: string): Builder | undefined {
  return builders.find((b) => b.slug === slug)
}

export function getBuildersByTrack(track: string): Builder[] {
  if (!track || track === 'all') return builders
  return builders.filter((b) => b.track === track)
}

export function getTopBuilders(count: number = 10): Builder[] {
  return builders.slice(0, count)
}

export function getTracks(): { value: string; label: string }[] {
  return [
    { value: 'all', label: '全部' },
    { value: 'Founder', label: 'Founder' },
    { value: 'Builder', label: 'Builder' },
    { value: 'KOL', label: 'KOL' },
    { value: 'Investor', label: 'Investor' },
  ]
}
